# Generated by Django 3.2 on 2023-07-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirmModel',
            new_name='Firm',
        ),
    ]
